<!-- Begin press release content -->

			
<div id="container" /*style="display:none;"*/>			
			<div id="media"><p style="font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Audio Segments</strong><br>
			</p>
						
<ul>

<li><a href=
"http://ricksmithshow.com/may-14,-2012-show">
Rick Smith Show interview with Eric Taylor (begins at about 1 hour 17 minutes)</a>
<div class="mediadate">May 14, 2012</div>
</li>

<li><a href=
"http://wearecitizenradio.com/2012/02/23/20120223-occupy-the-sec-inside-the-privatized-prison-industry/">
Citizen Radio interview with Alexis Goldstein and Elizabeth Friedrich (begins at about 32 minutes)</a>
<div class="mediadate">February 23, 2012</div>
</li>

<li><a href=
"http://ricksmithshow.com/february-15,-2012-show">
Rick Smith Show Interview with Alexis Goldstein (begins at about 1 hour 40 minutes)</a>
<div class="mediadate">February 15, 2012</div>
</li>








</ul>


</div>
</div>
<!-- End press release content -->


