			<div id="blogo">
			<img src="http://occupythesec.org/img/logob1.png" width="288" height="80" class="centerlogo" align="middle">
			</div>
			<div id="footer">
				<footer>
				<div class="centerfooter">
					<div id="footer1">
						<span class="footerheader">Resources</span><br>
						<a href="http://www.regulations.gov/">Regulations.gov</a><br>
						<a href="http://www.gpo.gov/fdsys/pkg/GPO-FCIC/pdf/GPO-FCIC.pdf">Financial Crisis Inquiry Report</a><br>
						<a href="http://thomas.loc.gov/cgi-bin/query/z?c111:h4173:/">Dodd Frank Act</a><br>
						<span class="footerheader1">Volcker Rule:</span> <a href="http://www.gpo.gov/fdsys/pkg/FR-2011-11-07/pdf/2011-27184.pdf">PDF </a><a href="http://govpulse.us/entries/2011/11/07/2011-27184/prohibitions-and-restrictions-on-proprietary-trading-and-certain-interests-in-and-relationships-with">HTML</a>	
					</div>
					<div id="footer2">
					
						<span class="footerheader">Proposed Rules</span><br>
						<a href="http://www.federalreserve.gov/newsevents/reform_proposals.htm">Federal Reserve</a><br>
						<a href="http://www.treasury.gov/initiatives/fsoc/rulemaking/Pages/open-notices.aspx">FSOC - Treasury</a><br>
						<a href="http://www.sec.gov/rules/proposed.shtml">SEC</a><br>
						<a href="http://comments.cftc.gov/PublicComments/ReleasesWithComments.aspx">CFTC</a><br>
						<a href="http://www.consumerfinance.gov/notice-and-comment/">CFPB</a><br>
						<a href="http://occ.gov/topics/laws-regulations/occ-regulations/for-public-comment.html">OCC</a>
					
					</div>
						
					<div id="footer3">
						<span class="footerheader">Political Allies</span><br>
						<a href="http://www.nycga.net/">NYCGA</a><br>
						<a href="http://alternativebanking.nycga.net">Alternative Banking - OWS</a><br>
						<a href="http://www.bettermarkets.com">Better Markets</a><br>
						<a href="http://ourfinancialsecurity.org">Americans for Financial Reform</a><br>
						<a href="http://www.citizen.org/Page.aspx?pid=2554">Public Citizen</a>
						
					</div>
					
					<div id="footer4">
						<span class="footerheader">Recommended Blogs</span><br>
						<a href="http://www.nycga.net/">Naked Capitalism</a><br>
						<a href="http://baselinescenario.com">The Baseline Scenario</a><br>
						<a href="http://blogs.reuters.com/felix-salmon/">Felix Salmons</a><br>
						<a href="http://blogs.reuters.com/alison-frankel/">Alison Frankel</a><br>
						<a class="fancybox" href="#moreblogs" title="More Good Blogs">And more here...</a>
						
					</div>
					
					<div id="footer5">
						<span class="footerheader">Other Links</span><br>
						<a href="http://www.nycga.net/groups/occupy-the-sec/">Our NYCGA Page</a><br>
						<a href="http://occupythesec.nycga.net/category/education/">Education Blog Posts</a><br>
	
						
					</div>
				</div>
					
				</footer>
			</div>
			
	<div id="moreblogs" style="width:400px; display:none;">
		<ul class="bloglist">
		<li><a href="http://www.ritholtz.com/blog/">The Big Picture</a></li>
		<li><a href="http://mathbabe.org">Math Babe (Cathy O'Neil's blog)</a></li>
		</ul>
	</div>


	</body>
</html>