<!-- Begin mailing list form -->
<div id="mright">
	<div id="list">
		<!--<p style="text-align:center;"><strong>Join Our Mailing List!</strong></p>-->
		<a name="mailing">
		<iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dE4zNWQ1N3JiRjh6UFVEVjR6Ym5TeUE6MA&c=000000" height="350" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
	</div>
</div>
<!-- End mailing list form -->


