<!-- Begin press release content -->

			
<div id="container" /*style="display:none;"*/>			
			<div id="media"><p style="font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Member Articles</strong><br>
			</p>
						
<ul>





<li><a href=
"http://www.americanbanker.com/bankthink/wall-street-sets-the-rules-for-regulators-1051745-1.html">
Wall Street Sets the Rules for Regulators</a>
<div class="by">Katya Grishakova and Elizabeth Friedrich</div>
<div class="mediadate">August 13, 2012 - <i>American Banker</i></div>
</li>

<li><a href=
"http://www.americanbanker.com/bankthink/Occupy-the-SEC-JPM-Jamie-Dimon-1049883-1.html">
SEC Must Thoroughly Investigate JPMorgan, Including Its CEO</a>
<div class="by">Akshat Tewary</div>
<div class="mediadate">June 6, 2012 - <i>American Banker</i></div>
</li>

<li><a href=
"http://www.americanbanker.com/bankthink/Tarullo-meeting-Federal-Reserve-counterparty-limit-1048954-1.html">
CEOs' Meeting with Tarullo Is Big Banks’ Version of May Day</a>
<div class="by">Elizabeth Friedrich</div>
<div class="mediadate">May 2, 2012 - <i>American Banker</i></div>
</li>

<li><a href=
"http://www.americanbanker.com/bankthink/Occupy-the-SEC-Volcker-rule-OWS-1046996-1.html">
Bank Lobby Cries over Volcker Rule, Regulators Try to Gut It</a>
<div class="by">Akshat Tewary</div>
<div class="mediadate">February 28, 2012 - <i>American Banker</i></div>
</li>








</ul>


</div>
</div>
<!-- End press release content -->


