<!-- Begin mailing list form -->
<div id="mediaright">

<p style="margin-left:40px;font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Categories</strong></p>
<div id="mediacategories">


<script src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript">
		var jQuery_latest = $.noConflict(true);
	</script>
<script>
$(document).ready(function(){
var str=location.href.toLowerCase();
$(".navigation li a").each(function() {
if (str.indexOf(this.href.toLowerCase()) > -1) {
 $("li.highlight").removeClass("highlight");
$(this).parent().addClass("highlight");
}
 });
 })
</script>
<ul class="navigation">
  <li class="highlight"><a href="/media/">OSEC in the News</a></li>
  <li><a href="/media/news/">Recent News</a></li>
  <li><a href="/media/articles/">Member Articles</a></li>
  <li><a href="/media/press-releases/">Press Releases</a></li>
  <li><a href="/media/video/">Video</a></li>
  <li><a href="/media/audio/">Audio</a></li>
 
</ul>



</div>

</div>
<!-- End mailing list form -->


