<!-- Begin media content -->



<div id="container">	





		
			<div id="media">

<script type="text/javascript">
$(document).ready(function () {
	$('#rss').rssfeed(['http://occupythesec.nycga.net/category/bad-ugly/feed/'], {
		limit: 1,
		sort: 'date'
	});
});
</script>
<p id="blog" style="margin-left:0px;font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Recent News</strong></p>
<div id="rss">

</div>


	

</div>
</div>
<!-- End media content -->


