
<div id="mleft">

	<p style="font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Latest Actions</strong></p>
	<div class="fb-like" style="padding-left:20px; padding-right:10px;" data-href="http://occupythesec.org" data-send="true" data-layout="button_count" data-width="250" data-show-faces="false" data-font="arial"></div>
<div style="vertical-align:0px; display:inline;"><a href="https://twitter.com/share" class="twitter-share-button" data-count="none">Tweet</a></div>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	


		<div id="announce">
		
		<!-- BEGIN ANNOUNCE -->
	  <div id="unsupportedBrowser">
	    <div id="warningText">


<p style="text-align:left;"><strong><h12>Opposition to Deregulation</h12></strong></p>
<p><span class="red">May 1, 2013</span>Occupy the SEC has analyzed a slew of bills that would gut various components of Title VII's swaps oversight. In response we sent a letter to the House Financial Services Committee with our recommendations. In general, OSEC recommends that the House forebear from passing premature amendments or modifications to the Dodd-Frank as the law has yet to be fully implemented or enforced.<a href="http://www.occupythesec.org/files/OSEC_Title_VII_Bills.pdf"> Read Letter.</a></em></p>

<p style="text-align:left;"><strong><h12>Lawsuit Filed Against Federal Regulators</h12></strong></p>
<p><span class="red">February 27, 2013</span>Occupy the SEC has filed a lawsuit in the Eastern District of New York against six federal agencies, over those agencies' delay in promulgating a Final Rulemaking in connection with the "Volcker Rule." Here is a <a href="http://occupythesec.org/files/OSECVolckerComplaint.pdf">pdf copy of the lawsuit.</a><br><em><a href="http://occupythesec.org/files/Complaintpressrelease.pdf">Press Release</a></em></p>

<p style="text-align:left;"><strong><h12>Money Market Reform</h12></strong></p>
<p><span class="red">February 15, 2013</span>We submitted a Comment Letter regarding the joint agency efforts to reform the money markets. The Financial Stability Oversight Council (FSOC) proposed three solutions which we <a href="http://occupythesec.org/files/MMFcomment.pdf">weighed in on.</a></p>


	    </div>
	  </div>
	  <br>
	  <br>
<!-- END ANNOUNCE -->
		<p style="font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Issues</strong></p>
			<p style="text-align:left;"><strong><h12>Volcker Rule</h12></strong></p>
			<p>  Last winter, Occupy the SEC submitted a 325 page letter to the SEC, FDIC, the Federal Reserve and the OCC, to comment on the
					<a href="https://www.federalregister.gov/articles/2011/11/07/2011-27184/prohibitions-and-restrictions-on-proprietary-trading-and-certain-interests-in-and-relationships-with">
						notice of proposed rulemaking for the Volcker Rule</a>. In our comment letter, we answered 244 out of 395 questions asked by the Agencies. Since then we have continued to opine on the rule's development. To read more about our Volcker-related actions <a href="../projects/#Volcker">click here.</a></p>
				
			<p>Even though the letter has been submitted you can still have your voice be heard by signing our petition. When you sign the petition all the regulators get a message automatically sent to them.  
			<!-- <form><a href="https://www.change.org/petitions/the-federal-reserve-fdic-occ-sec-cftc-protect-the-people-not-the-banks-enforce-a-strong-volcker-rule"><input type="button" class="button_yellow" value="SIGN PETITION" /></a></form></p>--><br>
		    <br>
		    
		    <p style="text-align:left;"><strong><h12>JOBS Act</h12></strong></p>
			<p>"JOBS" stands for "Jumpstart Our Business Startups" and it is a misnomer. It should have been named something less misleading, like the TOYS Act - Take Off Your SOX Act (Sarbanes-Oxley). Rather than directly promoting employment, the Act removes important investor protections and frees Wall Street and allegedly small companies from compliance with Sarbanes-Oxley. For more about what we think of this Act see our public <a href="../files/JOBSAct.pdf">Comment Letter</a> we submitted to the SEC.<a href="../projects/#JPM"> More here.</a></p>
			<br>
			
			<p style="text-align:left;"><strong><h12>LIBOR Scandal</h12></strong></p>
			<p>We submitted a <a href="http://occupythesec.nycga.net/2012/07/16/the-need-for-criminal-prosecutions-to-redress-the-bank-excesses-of-the-libor-scandal/">Letter to SEC Chairman Mary Schapiro</a> requesting a criminal investigation for market manipulation.</p> Read more<a href="../projects/"> here.</a></p>
			<br>
			
			<p style="text-align:left;"><strong><h12>J.P. Morgan / Chief Investment Office Losses</h12></strong></p>
			<p>
    		<a href="../files/LetterstoCongress.pdf">Commentary and questions</a> for House Banking Services Committee questioning of Jamie Dimon after JP Morgan lost billions on a series of related trades.
			</p>
			<p>We had a lot of to say about this event. In June we submitted a flurry of letters to various officials. To find out more <a href="../projects/">click here.</a>
		</div>
</div>