<!-- Begin media content -->

			
<div id="container">			
			<div id="media"><p style="font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>OSEC in the News</strong><br>
			</p>
						

<ul>


<li><a href=
"http://www.law360.com/articles/419207/high-court-ruling-puts-sec-actions-on-strict-timetable-">
High Court Ruling Puts SEC Actions On Strict Timetable </a>
<div class="mediadate">February 27, 2013 - <i>Law360</i></div>
</li>

<li><a href=
"http://www.law360.com/banking/articles/419217/sec-watchdog-sues-feds-over-volcker-rule-delay">
SEC Watchdog Sues Feds Over Volcker Rule Delay</a>
<div class="mediadate">February 27, 2013 - <i>Law360</i></div>
</li>

<li><a href=
"http://www.reuters.com/article/2013/02/27/financial-regulation-occupy-idUSL1N0BR7MZ20130227">
Reform Group Sues U.S. Regulators ver Volcker Rule Delays</a>
<div class="mediadate">February 27, 2013 - <i>Reuters</i></div>
</li>

<li><a href=
"http://newsandinsight.thomsonreuters.com/Legal/News/2013/02_-_February/Ex-SEC_officials_to_risk_council__Back_off_on_money_funds/#sthash.kulHDt9k.dpuf">
Ex-SEC Officials to Risk Council: Back Off on Money Funds</a>
<div class="mediadate">February 21, 2013 - <i>Thomson Reuters</i></div>
</li>

<li><a href=
"http://www.law360.com/articles/412605/sec-pick-may-face-questions-over-troubling-defense-work">
SEC Pick May Face Questions Over ‘Troubling’ Defense Work</a>
<div class="mediadate">February 4, 2013 - <i>Law360</i></div>
</li>

<li><a href=
"http://economix.blogs.nytimes.com/2012/12/20/last-ditch-attempt-to-derail-volcker-rule/">
Last-Ditch Attempt to Derail Volcker Rule</a>
<div class="mediadate">December 20, 2012 - <i>The New York Times</i></div>
</li>


<li><a href=
"http://www.nytimes.com/video/2012/11/06/us/politics/100000001887820/voters-cast-their-ballots.html">
Voters Cast Their Ballots</a>
<div class="mediadate">November 6, 2012 - <i>The New York Times</i></div>
</li>

<li><a href=
"http://blogs.reuters.com/felix-salmon/2012/09/18/the-importance-of-occupy/">
The Importance of Occupy</a>
<div class="mediadate">September 18, 2012 - <i>Reuters</i></div>
</li>

<li><a href=
"http://www.aljazeera.com/programmes/peopleandpower/2012/09/2012912134638276495.html">
Prosecuting Wall Street  </a>
<div class="mediadate">September 14, 2012 - <i>Al-Jazeera</i></div>
</li>

<li><a href=
"http://www.theglobeandmail.com/report-on-business/international-business/us-business/the-comeback-of-occupy-wall-street/article4546605/?cmpid=rss1
">
The Comeback of Occupy Wall Street </a>
<div class="mediadate">September 14, 2012 - <i>The Globe and Mail</i></div>
</li>

<li><a href=
"http://www.fa-mag.com/news/occupy-wall-street-protesters-plan-traffic-blockade-amid-participant-burnout-11774.html">
Occupy Wall Street Protesters Plan Traffic Blockade Amid Participant Burnout</a>
<div class="mediadate">August 29, 2012 - <i>Financial Advisor</i></div>
</li>

<li><a href=
"http://www.law360.com/banking/articles/363653/despite-weill-s-words-breaking-up-banks-won-t-be-easy">
Despite Weill's Words, Breaking Up Banks Won't Be Easy</a>
<div class="mediadate">July 25, 2012 - <i>Law360</i></div>
</li>

<li><a href=
"http://www.lemonde.fr/a-la-une/article/2012/07/13/les-rebelles-de-wall-street_1733520_3208.html">
Les Rebelles de Wall Street</a>
<div class="mediadate">July 13, 2012 - <i>Le Monde</i></div>
</li>

<li><a href=
"http://www.law360.com/articles/350137/uk-s-broad-ring-fencing-proposal-may-outshine-volcker-rule">
UK's Broad Ring-Fencing Proposal May Outshine Volcker Rule</a>
<div class="mediadate">June 14, 2012 - <i>Law360</i></div>
</li>


<li><a href=
"http://news.firedoglake.com/2012/06/13/dimon-to-be-contrite-yet-steadfast-in-senate-banking-testimony/">
Dimon to Be Contrite Yet Steadfast in Senate Banking Testimony</a>
<div class="mediadate">June 13, 2012 - <i>Fire Dog Lake</i></div>
</li>


<li><a href=
"http://www.presstv.com/usdetail/246012.html">
'Occupy the SEC' Protest US Banking System</a>
<div class="mediadate">June 13, 2012 - <i>Press TV</i></div>
</li>


<li><a href=
"http://www.guardian.co.uk/business/blog/2012/jun/13/jp-morgan-jamie-dimon-senate-live?newsfeed=true">
JP Morgan Boss Jamie Dimon Faces Down Senate Critics – as it Happened</a>
<div class="mediadate">June 13, 2012 - <i>The Guardian</i></div>
</li>

<li><a href=
"http://nymag.com/daily/intelligencer/2012/06/jamie-dimon-can-explain-everything.html">
Jamie Dimon Can Explain Everything</a>
<div class="mediadate">June 13, 2012 - <i>New York Magazine</i></div>
</li>

<li><a href=
"http://www.guardian.co.uk/business/2012/jun/12/columbia-jp-morgan-jamie-dimon">
Columbia in a Tangle Over Links to Embattled JP Morgan Boss Dimon</a>
<div class="mediadate">June 12, 2012 - <i>The Guardian</i></div>
</li>


<li><a href=
"http://www.huffingtonpost.com/2012/06/12/occupy-the-sec-jamie-dimon_n_1591465.html">
'Occupy The SEC' Has Exactly 11 Questions For Jamie Dimon</a>
<div class="mediadate">June 12, 2012 - <i>Huffington Post</i></div>
</li>


<li><a href=
"http://www.huffingtonpost.com/2012/05/24/occupy-wall-street-jed-rakoff-sec_n_1543263.html">
Occupy Wall Street-Affiliated Group Sides With Federal Judge Jed Rakoff In SEC Feud </a>
<div class="mediadate">May 24, 2012 - <i>Huffington Post</i></div>
</li>

<li><a href=
"http://www.americanlawyer.com/digestTAL.jsp?id=1202555773072&Rakoff_Gets_Amicus_Support_from_Occupy_Wall_Street_in_Citi_Appeal&slreturn=20130025000905">
Rakoff Gets Amicus Support from Occupy Wall Street in Citi Appeal </a>
<div class="mediadate">May 23, 2012 - <i>The Am Law Litigation Daily</i></div>
</li>

<li><a href=
"http://english.cntv.cn/program/newshour/20120517/111200.shtml">
Two Shareholders File Lawsuits Against JPMorgan </a>
<div class="mediadate">May 17, 2012 - <i>CNTV</i></div>
</li>

<li><a href=
"http://video.cnbc.com/gallery/?video=3000090186&play=1">
'Occupy Wall Street' Weighs In on JPMorgan </a>
<div class="mediadate">May 14, 2012 - <i>CNBC</i></div>
</li>

<li><a href=
"http://www.guardian.co.uk/business/2012/may/14/jp-morgan-shareholder-showdown-tempest">
JP Morgan Boss to Face Shareholders Over $2bn 'Tempest in a Teapot'</a>
<div class="mediadate">May 14, 2012 - <i>The Guardian</i></div>
</li>

<li><a href=
"http://www.youtube.com/watch?v=HoII0ywQtMQ">
Occupy the SEC Takes on Big Banks and the London Whale </a>
<div class="mediadate">April 27, 2012 - <i>RT</i></div>
</li>


<li><a href=
"http://www.bloomberg.com/news/2012-03-01/occupy-the-sec-writes-new-volcker-rule-script-commentary-by-susan-antilla.html">
Occupy Vigilantes Write New Volcker Script</a>
<div class="mediadate">March 3, 2012 - <i>Bloomberg View</i></div>
</li>

<li><a href=
"http://www.counterpunch.org/2012/02/20/occupy-the-sec-pitches-an-extreme-makeover-of-wall-street/">
Occupy the SEC Pitches An Extreme Makeover of Wall Street</a>
<div class="mediadate">February 20, 2012 - <i>Counter Punch</i></div>
</li>



<li><a href=
"http://blogs.wsj.com/deals/2012/02/15/occupy-wall-street-comes-to-the-aid-of-volcker-rule/">
Occupy Wall Street Comes to the Aid of Volcker Rule</a>
<div class="mediadate">February 15, 2012 - <i>Wall Street Journal</i></div>
</li>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
 

$(document).ready(function(){
 
        $(".slidingDiv").hide();
        $(".show_hide").show();
 
    $('.show_hide').click(function(){
    $(".slidingDiv").slideToggle();
    });
 
});


</script>
<a href="#1" onclick="this.style.display='none';" class="show_hide" style="color: #333; background-color:white; padding:5px 10px 5px 10px; border: 1px solid rgb(37,83,133); position:relative; top:15px; border-radius:3px;">More News</a>
<a name="hola"></a>


<div class="slidingDiv">

<li><a href=
"http://blogs.reuters.com/felix-salmon/2012/02/14/occupys-amazing-volcker-rule-letter/">
Occupy’s amazing Volcker Rule letter</a>
<div class="mediadate">February 14, 2012 - <i>Reuters</i></div>
</li>

<li><a href=
"http://rortybomb.wordpress.com/2012/02/16/an-interview-with-occupy-the-sec-on-the-creation-of-their-volcker-rule-comment-letter/">
An Interview with Occupy the SEC on the Creation of their Letter</a>
<div class="mediadate">February 16, 2012 - <i>Rortybomb</i></div>
</li>

<li><a href=
"http://www.ibtimes.com/articles/299365/20120215/occupy-wall-street-volcker-rule-sec.htm">
Occupy Wall Street Group Offers Detailed Critique of Volcker Rule</a>
<div class="mediadate">February 15, 2012 - <i>International Business Times</i></div>
</li>

<li><a href=
"http://www.efinancialnews.com/story/2012-02-15/occupy-the-sec-volcker-funds-response?mod=sectionheadlines-TT-AM">
Occupy Attacks Asset Management Loopholes</a>
<div class="mediadate">February 15, 2012 - <i>eFinancial News</i></div>
</li>

<li><a href=
"http://www.law.com/jsp/cc/PubArticleCC.jsp?id=1202542598080&Occupy_the_SEC_Goes_Big_on_the_Volcker_Rule">
OSEC Goes Big on the Volcker Rule</a>
<div class="mediadate">February 17, 2012 - <i>Corporate Counsil</i></div>
</li>

<li><a href=
"http://motherjones.com/mojo/2012/02/occupy-sec-letter-volcker-rule">
In a 325-Page SEC Letter, Occupy's Finance Gurus Take on Wall Street Lobbyists </a>
<div class="mediadate">February 14, 2012 - <i>Mother Jones</i></div>
</li>

<li><a href=
"http://wonkette.com/463789/you-must-read-the-occupiers-325-page-comment-to-the-sec">
You Must Read The Occupiers’ 325-Page Comment To The SEC</a>
<div class="mediadate">February 15, 2012 - <i>Wonkette</i></div>
</li>


<li><a href=
"http://www.businessweek.com/finance/occupy-the-sec-weighs-in-on-the-volcker-rule-02142012.html">
Occupy the SEC Weighs In on the Volcker Rule</a>
<div class="mediadate">February 14, 2012 - <i>Business Week</i></div>
</li>



<li><a href=
"http://www.dailykos.com/story/2012/02/15/1064998/-RADICALS-OWS-Marches-In-Support-Of-Paul-Volcker?detail=hide&via=blog_805357">
RADICALS? OWS Marches In Support Of Paul Volcker</a>
<div class="mediadate">February 15, 2012 - <i>Daily KOS</i></div>
</li>




<script type="text/javascript">
 

$(document).ready(function(){
 
        $(".slidingDiv2").hide();
        $(".show_hide2").show();
 
    $('.show_hide2').click(function(){
    $(".slidingDiv2").slideToggle();
    });
 
});


</script>
<a href="#2" onclick="this.style.display='none';" class="show_hide2" style="color: #333; background-color:white; padding:5px 10px 5px 10px; border: 1px solid rgb(37,83,133); position:relative; top:15px; border-radius:3px;">More…</a>
<a name="allo"></a>


<div class="slidingDiv2">

<li><a href=
"http://www.americanbanker.com/morningscan/Morning-Scan-1046694-1.html)%20and%20here%20(http://www.americanbanker.com/the-scan/the-scan-wednesday-february-15-2012-1046695-1.html">
Morning Scan</a>
<div class="mediadate">February 15, 2012 - <i>American Banker</i></div>
</li>

<li><a href=
"http://www.buzzfeed.com/rosiegray/occupy-the-sec-releases-325-page-comment-letter">
“Occupy The Sec” Releases 325-Page Comment Letter On The Volcker Rule</a>
<div class="mediadate">February 14, 2012 - <i>Buzzfeed</i></div>
</li>

<li><a href=
"http://www.thecenterlane.com/?tag=occupy-the-sec">
Occupy Movement Gets Some Respect</a>
<div class="mediadate">February 16, 2012 - <i>The Center Lane</i></div>
</li>

<li><a href=
"http://www.compliancebuilding.com/2012/02/15/occupy-the-sec-2/">
Occupy the SEC</a>
<div class="mediadate">February 15, 2012 - <i>Compliance Building</i></div>
</li>

<li><a href=
"http://compliancesearch.com/compliancex/volcker-rule/occupy-sec-all-in-for-volcker-rule/">
Occupy SEC All in for Volcker Rule</a>
<div class="mediadate">February 15, 2012 - <i>Compliance Search</i></div>
</li>

<li><a href=
"http://www.thedailybeast.com/articles/2012/02/15/occupy-wall-street-breaks-up-with-bank-of-america-on-valentine-s-day.html">
Occupy Wall Street Breaks Up With Bank of America on Valentine’s Day</a>
<div class="mediadate">February 15, 2012 - <i>The Daily Beast</i></div>
</li>

<li><a href=
"http://dealbreaker.com/2012/02/the-volcker-rule-will-come-too-late-for-kaufman-bros/">
The Volcker Rule Will Come Too Late For Kaufman Bros</a>
<div class="mediadate">February 14, 2012 - <i>Deal Breaker</i></div>
</li>

<li><a href=
"http://www.efinancialnews.com/story/2012-02-15/occupy-the-sec-volcker-funds-response?mod=sectionheadlines-TT-AM)%20and%20here%20(http://www.efinancialnews.com/story/2012-02-15/occupy-wall-street-akshat-tewary-on-325-page-response-to-volcker">
Occupy Attacks Asset Management Loopholes</a>
<div class="mediadate">February 15, 2012 - <i>eFinancial Times</i></div>
</li>

<li><a href=
"http://www.fool.com/investing/general/2012/02/15/finally-something-i-can-agree-with-citigroup-about.aspx">
Finally, Something I Can Agree With Citigroup About!</a>
<div class="mediadate">February 15, 2012 - <i>The Motley Fool</i></div>
</li>

<li><a href=
"http://news.firedoglake.com/2012/02/14/citizen-lobbyists-occupy-the-sec-delivers-comment-letter-for-volcker-rule/">
Citizen Lobbyists: Occupy the SEC Delivers Comment Letter for Volcker Rule</a>
<div class="mediadate">February 14, 2012 - <i>Firedog Lake</i></div>
</li>









<script type="text/javascript">
 

$(document).ready(function(){
 
        $(".slidingDiv3").hide();
        $(".show_hide3").show();
 
    $('.show_hide3').click(function(){
    $(".slidingDiv3").slideToggle();
    });
 
});


</script>
<a href="#3" onclick="this.style.display='none';" class="show_hide3" style="color: #333; background-color:white; padding:5px 10px 5px 10px; border: 1px solid rgb(37,83,133); position:relative; top:15px; border-radius:3px;">More…</a>
<a name="allo"></a>


<div class="slidingDiv3">

<li><a href=
"http://articles.latimes.com/2012/feb/15/business/la-fi-volcker-rule-20120215">
Regulators weigh massive public input on 'Volcker rule'</a>
<div class="mediadate">February 15, 2012 - <i>LA Times</i></div>
</li>


<li><a href=
"http://www.marketwatch.com/story/volcker-others-clash-on-speculative-trading-rule-2012-02-13?dist=afterbell">
Volcker, others clash on speculative trading rule</a>
<div class="mediadate">February 13, 2012 - <i>Market Watch</i></div>
</li>


<li><a href=
"http://www.mybanktracker.com/news/2012/02/16/occupy-sec-wonky-volcker-rule/">
Occupy Gets Wonky; Files Lengthy Tome on Volcker Rule</a>
<div class="mediadate">February 16, 2012 - <i>My Bank Tracker</i></div>
</li>

<li><a href=
"http://www.nakedcapitalism.com/2012/02/occupy-the-secs-comment-letter-objects-to-excuses-for-watering-down-volcker-rule-ows.html">
Occupy the SEC’s Comment Letter Objects to Excuses for Watering Down Volcker Rule</a>
<div class="mediadate">February 14, 2012 - <i>Naked Capitalism</i></div>
</li>

<li><a href=
"http://reason.org/blog/show/occupy-the-sec">
Occupy the SEC</a>
<div class="mediadate">February 15, 2012 - <i>Reason Foundation</i></div>
</li>

<li><a href=
"http://www.salon.com/2012/02/15/occupy_defends_the_volcker_rule/singleton/">
Occupy defends the Volcker Rule: Radical protesters are reborn as policy analysts; they tell the SEC to curb Wall Street speculators</a>
<div class="mediadate">February 15, 2012 - <i>Salon</i></div>
</li>

<li><a href=
"http://http//www.slate.com/blogs/moneybox/2012/02/14/occupy_the_sec_releases_325_page_comment_letter_on_quot_volcker_rule_quot_proposals.html">
Occupy the SEC Releases 325 Page Comment Letter on 'Volcker Rule' Proposals</a>
<div class="mediadate">February 14, 2012 - <i>Slate</i></div>
</li>

<li><a href=
"http://www.thestreet.com/story/11420847/1/3-reasons-banks-are-worried-about-the-volcker-rule.html">
3 Ways Banks Will Be Killed by New Rules</a>
<div class="mediadate">February 16, 2012 - <i>The Street</i></div>
</li>

<li><a href=
"http://swampland.time.com/2012/02/14/occupy-the-regulatory-open-comment-period/">
Occupy the Regulatory Open Comment Period!</a>
<div class="mediadate">February 14, 2012 - <i>Time</i></div>
</li>



<script type="text/javascript">
 

$(document).ready(function(){
 
        $(".slidingDiv4").hide();
        $(".show_hide4").show();
 
    $('.show_hide4').click(function(){
    $(".slidingDiv4").slideToggle();
    });
 
});


</script>
<a href="#4" onclick="this.style.display='none';" class="show_hide4" style="color: #333; background-color:white; padding:5px 10px 5px 10px; border: 1px solid rgb(37,83,133); position:relative; top:15px; border-radius:3px;">More…</a>
<a name="allo"></a>


<div class="slidingDiv4">




<li><a href=
"http://www.huffingtonpost.com/2012/02/14/occupy-sec-volcker-rule_n_1276903.html">
Occupy The SEC Marches In Support Of A Strong Volcker Rule</a>
<div class="mediadate">February 12, 2012 - <i>Huffington Post</i></div>
</li>

<li><a href=
"http://occupiedmedia.us/2012/02/occupy-the-volcker-rule/">
Occupy the Volcker Rule</a>
<div class="mediadate">February 4, 2012 - <i>Occupied Wall Street Journal</i></div>
</li>

<li><a href=
"http://www.thenation.com/article/165899/occupying-policy">
Occupying Policy</a>
<div class="mediadate">January 26, 2012 - <i>The Nation</i></div>
</li>


</div>










</div>

</ul>
</div>
</div>
<!-- End media content -->


