<!-- Begin media content -->



<div id="container">	





		
			<div id="media">

<p id="blog" style="margin-left:0px;font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Proposed Rules</strong></p>

<h4>Select an agency from the list below</h4>
<select id="menu">
	<option value="https://www.federalregister.gov/articles/search.rss?conditions%5Bagency_ids%5D=466&conditions%5Bpublication_date%5D%5Bgte%5D=11%2F19%2F2012&conditions%5Btype%5D=PRORULE&order=newest">Securities Exchange Commission</option>
	<option value="https://www.federalregister.gov/articles/search.rss?conditions%5Bagency_ids%5D=188&conditions%5Bpublication_date%5D%5Bgte%5D=11%2F19%2F2012&conditions%5Btype%5D=PRORULE&order=newest">Federal Reserve</option>
	<option value="https://www.federalregister.gov/articles/search.rss?conditions%5Bagency_ids%5D=573&conditions%5Bpublication_date%5D%5Bgte%5D=11%2F19%2F2012&conditions%5Btype%5D=PRORULE&order=newest">Consumer Financial Protection Bureau</option>
	<option value="https://www.federalregister.gov/articles/search.rss?conditions%5Bagency_ids%5D=77&conditions%5Bpublication_date%5D%5Bgte%5D=11%2F19%2F2012&conditions%5Btype%5D=PRORULE&order=newest">Commodity Futures Trading Commission</option>
	<option value="https://www.federalregister.gov/articles/search.rss?conditions%5Bagency_ids%5D=164&conditions%5Bpublication_date%5D%5Bgte%5D=11%2F19%2F2012&conditions%5Btype%5D=PRORULE&order=newest">Federal Deposition Insurance Corporation</option>
	<option value="https://www.federalregister.gov/articles/search.rss?conditions%5Bagency_ids%5D=80&conditions%5Bpublication_date%5D%5Bgte%5D=11%2F19%2F2012&conditions%5Btype%5D=RULE&order=newest">Office of the Comptroller of the Currency</option>
</select>

<!-- <h4>Recent Proposed Rules</h4> -->
<div id="feed"></div>





	




</div>
</div>
<!-- End media content -->


