<!-- Begin press release content -->

			
<div id="container" /*style="display:none;"*/>			
			<div id="media"><p style="font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Press Releases</strong><br>
			</p>
						
<ul>
<li><a href=
"http://www.occupythesec.org/files/Complaintpressrelease.pdf">
Occupy the SEC has filed a lawsuit in the Eastern District of New York against six federal agencies, over those agencies' delay in promulgating a Final Rulemaking in connection with the "Volcker Rule"</a>
<div class="mediadate">February 27, 2013</div>
</li>
<li><a href=
"http://www.occupythesec.org/files/MMF_pressrelease.pdf">
Occupy the SEC Submits Comment Letter to the Financial Stability Oversight Council (FSOC) on Proposed Money Market Regulations</a>
<div class="mediadate">February 21, 2013</div>
</li>
<li><a href=
"http://www.occupythesec.org/files/Whitepressrelease.pdf">
Occupy the SEC Submits Letter to the Senate Committee on Banking, Housing, and Urban Affaires Regarding the Nomination Hearing of Mary Jo White to Head the SEC</a>
<div class="mediadate">February 1, 2013</div>
</li>
<li><a href=
"http://www.occupythesec.org/files/Gabelli-press-release.pdf">
Occupy the SEC Files Amicus Brief with the U.S. Supreme Court in <i>Gabelli v. SEC</i></a>
<div class="mediadate">December 13, 2012</div>
</li>
<li><a href=
"http://occupythesec.nycga.net/2012/11/05/press-release-occupy-the-sec-and-ows-alternative-banking-working-group-call-for-greater-transparency-in-the-ongoing-formulation-of-money-market-fund-regulations/">
Occupy the SEC and OWS-Alternative Banking Working Group call for the S.E.C. and the Department of the Treasury to increase transparency in the ongoing formulation of money market fund regulations</a>
<div class="mediadate">November 15, 2012</div>
</li>
<li><a href=
"http://occupythesec.nycga.net/2012/07/16/the-need-for-criminal-prosecutions-to-redress-the-bank-excesses-of-the-libor-scandal/">
Occupy the SEC issued a release calling for
criminal prosecutions over LIBOR manipulation and fraud</a>
<div class="mediadate">July 16, 2012</div>
</li>
<li><a href=
"http://www.occupythesec.org/files/PressRelease.pdf">
Occupy the SEC and OWS-Alternative Banking
Working Group call for the S.E.C. to investigate Jamie Dimon under Sarbanes-Oxley, and make
a criminal referral to the Department of Justice</a>
<div class="mediadate">June 4, 2012</div>
</li>
<li><a href=
"http://www.occupythesec.org/files/Press%20Release-OSEC-JPM-Loss.pdf">
JP Morgan's London Whale Fiasco highlights
the need for a strong Volcker Rule </a>
<div class="mediadate">May 11, 2012</div>
</li>

</div>
</div>
<!-- End press release content -->


