<!-- Begin mailing list form -->
<div id="mright">

<script type="text/javascript">
$(document).ready(function () {
	$('#rss').rssfeed(['http://occupythesec.nycga.net/?feed=rss'], {
		limit: 6,
		sort: 'date'
	});
});
</script>
<p style="margin-left:40px;font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;"><strong>Recent Blog Posts</strong></p>
<div id="rss">

</div>

	<div id="list">
		<!--<p style="text-align:center;"><strong>Join Our Mailing List!</strong></p>-->
		<a name="mailing">
		<iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dE4zNWQ1N3JiRjh6UFVEVjR6Ym5TeUE6MA&c=000&bc=transparent" height="350" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
	</div>
</div>
<!-- End mailing list form -->


