<!-- Begin press release content -->

			
<div id="container" /*style="display:none;"*/>			
			<div id="media"><p style="font-size: 1.3em; text-align:left; text-decoration:none; font-variant:normal;" class="blackyellow"><strong>Video Segments</strong><br>
			</p>
						
<ul>


<li><a href=
"http://www.youtube.com/watch?v=uzragHkSXGw&feature=youtu.be">
RTAmerica: Occupy the SEC sues the government over 'Volcker Rule'</a>
<div class="mediadate">March 1, 2013</div>
</li>
<li><a href=
"http://www.nytimes.com/video/2012/11/06/us/politics/100000001887820/voters-cast-their-ballots.html">
Occupy the SEC's Akshat Tewary on The New York Times, chiming in on the presidential race</a>
<div class="mediadate">November 6, 2012</div>
</li>
<li><a href=
"http://video.cnbc.com/gallery/?video=3000090186&amp;play=1">
Occupy the SEC's Akshat Tewary on CNBC, talking about the JP Morgan "London Whale" debacle</a>
<div class="mediadate">July 16, 2012</div>
</li>
<li>A multi-part interview on Felix TV with Felix Salmon:<a href=
"http://www.occupythesec.org/files/PressRelease.pdf">
</a>
<div class="mediadate">June 4, 2012</div></li>
<ol>
<li><a href=
"http://www.reuters.com/video/2012/02/18/reuters-tv-occupy-movement-takes-on-sec-volcker-rul?videoId=230392129&amp;videoChannel=117757">
Part 1: Occupy Movement Takes on the Volcker Rule</a></li>
<li><a href=
"http://www.reuters.com/video/2012/02/21/reuters-tv-occupy-the-sec-proprietary-trading-from?videoId=230555075&amp;videoChannel=117757">
Part 2: Proprietary Trading from the Discount Window</a></li>
<li><a href=
"http://www.reuters.com/video/2012/02/22/reuters-tv-the-occupy-movement-gets-sophisticated-f?videoId=230604790&amp;videoChannel=117757">
Part 3: Where we talk Carried Interest and Intentionality</a></li>
</ol>
<li><a href=
"http://english.cntv.cn/program/newshour/20120517/111200.shtml">
Occupy the SEC on CCTV: Two
Shareholders File Lawsuits Against JP Morgan</a>
<div class="mediadate">May 17, 2012</div>
</li>
<li><a href=
"http://www.youtube.com/watch?v=HoII0ywQtMQ">
Occupy the SEC on RTV: Occupy the SEC Takes
on Big Banks and the London Whale </a>
<div class="mediadate">May 11, 2012</div>
</li>
<li><a href=
"http://www.msnbc.msn.com/id/21134540/vp/46446446#46446446">
Occupy the SEC's Alexis Goldstein on UP with Chris Hayes</a>
<div class="mediadate">May 11, 2012</div>
</li>
<li><a href=
"http://www.youtube.com/watch?v=MWrewxA1t8c">
Occupy the SEC on Democracy Now! defending the Volcker Rule</a>
<div class="mediadate">May 11, 2012</div>
</li>


</ul>


</div>
</div>
<!-- End press release content -->


