<a name="Volcker"></a>
<div id="projects">



<p>
    <strong><h12>Volcker Rule</h12></strong>
</p>
<p>
    The Volcker Rule is our era’s version of Glass-Steagall Act. Glass-Steagall was passed during the Great Depression, and separated commercial and investment banking in order to stabilize the banking system. For much of the 20th century, the Act was a success - both the financial sector and the economy avoided a repeat of the Great Depression. But the relentless pressure for deregulation led to the steady dismantling of the Act’s provisions, culminating with its repeal in 1999 by the Graham-Leach-Bliley Act. Within a decade, both the markets and the economy plunged.<br><br>
  	Like Glass-Steagall, the Volcker Rule attempts to restore stability to the banking system by strictly controlling the exposure of commercial banks to volatile financial market activity. If implemented properly, the Volcker Rule would be a big step toward stabilizing markets and the banking system and reducing the risk of more taxpayer-funded bailouts.<br><br>
	Both the Volcker Rule and the larger Dodd-Frank Act have met with stiff resistance from the financial industry and sympathetic lawmakers. Fortunately, the regulatory process provides an opportunity for concerned citizens to express their views. When regulators released a proposed implementation of the regulation, Occupy the SEC submitted a Comment Letter and followed that with meetings with regulators to present our arguments on how to make the rule better. The extended rulemaking process has given lobbyists multiple opportunities to push back on the rule’s development, which is why we remain engaged in commenting on the process. 
</p>
<p>
    <span class="red">September 7, 2012</span> <a href="../files/OSEC-Volcker-Alternative-Comment-Letter.pdf">Comment Letter</a> to House Financial Services Committee on possible alternatives to the Volcker Rule.<br/>
    <em><a href="http://occupythesec.nycga.net/2012/09/11/occupy-the-sec-submits-comments-to-the-house-financial-services-committee-in-response-to-chairman-bachus-request-for-legislative-proposals/">Press Release</a></em>
</p>
<p>
    <span class="red">April 23, 2012</span> Occupy the SEC held a<a href="../files/April23rd2012VolckerBriefing.pdf"> Congressional Staff Briefing.</a>
    We also held a separate press briefing at 4pm. Here is coverage of that event at <a href="http://www.youtube.com/watch?v=HoII0ywQtMQ&amp;feature=player_embedded">RT</a> and <a href="http://www.washingtonpost.com/blogs/ezra-klein/post/occupy-the-regulatory-system/2012/04/27/gIQAjo21lT_blog.html">the Washington Post.</a>
</p>
<p>
    <span class="red">April 16, 2012</span> <a href="http://comments.cftc.gov/PublicComments/ViewComment.aspx?id=57409&SearchText=occupy">Comment Letter</a> to the CFTC on proposed implementation of the Volcker Rule.
</p>
<p>
    <span class="red">January 30, 2012</span> <a href="../letter/OSEC%20-%20OCC-2011-14%20-%20Comment%20Letter.pdf">Comment Letter</a> to the SEC, FDIC, OCC and Federal Reserve on proposed implementation of the Volcker Rule.

</p>
<p>
    <span class="red">January 17, 2012</span> <a href="http://www.scribd.com/doc/78595303/Occupy-Wall-Street-Volcker-Rule-Letter-to-House-Financial-Services-Committee">Letter</a> to the House Committee on Financial Services regarding their examination of the impact of the Volcker Rule on markets, businesses, investors and job creation.

</p>
<br>
<p>
    <strong><h12>Money Market Funds</h12></strong>
</p>
<p>
    Money market funds were left out of the Dodd-Frank Act, and remain a source of systemic risk to the U.S. economy. The Financial Stability Oversight Council is using its authority to drive regulation for the first time since its creation by the Dodd-Frank Act, leading OSEC to get involved in the process of commenting on new proposed regulations. Presently, we are engaged in drafting a Comment Letter on three proposed solutions to money market reform. 
</p>
<p>
    <span class="red">November 5, 2012</span> <a href="http://occupythesec.nycga.net/2012/11/05/press-release-occupy-the-sec-and-ows-alternative-banking-working-group-call-for-greater-transparency-in-the-ongoing-formulation-of-money-market-fund-regulations/">Letter</a> to Timothy Geithner and Mary Schapiro on the need for transparency in the formation of rules.
</p>
<br>

<p>
    <strong><h12>Gabelli et al v. SEC</h12></strong>
</p>

<p>Occupy the SEC submitted an Amicus Brief in the case of <a href="http://www.supremecourt.gov/Search.aspx?FileName=/docketfiles/11-1274.htm"><i>Gabelli v. SEC</i></a>, which is currently before the Supreme Court. The Court will be making a ruling about when the statute of limitations clock begins for certain fraud actions brought by the government - from the time the fraud was last committed or from the time the fraud was discovered. We contend - along with the SEC - that the timing should accrue from discovery of the fraud.
</p>

<p>
    <span class="red">December 1, 2012</span> <a href="http://www.occupythesec.org/files/OSEC_Gabelli_Amicus.pdf">Amicus Brief</a> submitted to Supreme Court.

</p>

<br>



<p>
    <strong><h12>JOBS Act</h12></strong>
</p>
<p>
    The misleadingly named JOBS Act releases so-called "emerging growth" companies from having to comply with the investor-protection requirements of Sarbanes Oxley (or SOX). Emerging growth companies are supposed to be fledgling businesses that are financially burdened by SOX compliancy. According to this Act, such businesses should have annual revenues of less than $1 billion. But is that really "emerging?" For more details read our whole Comment Letter.</p>
</p>
<p>
    <span class="red">July 31, 2012</span> <a href="../files/JOBSAct.pdf">Comment Letter</a> to the SEC on proposed implementation of the JOBS Act.
<a name="JPM"></a>
</p>

<br>

<p>
    <strong><h12>J.P. Morgan/London Whale Trading Debacle</h12></strong>
</p>
<p>
    In the spring of 2012, J.P. Morgan lost billions of dollars on a series of speculative trades. done under the auspices of what the bank claimed was "portfolio hedging." That classification put the trades into a category that was explicitly exempted from the proposed draft of the Volcker Rule. Three guesses who lobbied heavily for the exemption. 
</p>


<p>
    <span class="red">July 25, 2012</span> <a href="../files/SOX_Letter.pdf">Letter to Schapiro</a> requesting Sarbanes-Oxley enforcement action against J.P. Morgan CEO Jamie Dimon. Also, we submitted a <a href="../files/HouseSOXLetter.pdf">letter</a> to the Financial Service Committee encouraging the Committee to 
    combat SOX violations more vigorously in the wake of the J.P. Morgan losses. 
</p>
<p>
    <span class="red">June 22, 2012</span> <a href="../files/LetterstoCongress.pdf">Commentary and questions</a> for House Banking Services Committee questioning of Jamie Dimon
</p>
<p>
    <span class="red">June 12, 2012</span> <a href="../files/DimonCommentLetter.pdf">Commentary and questions</a> for Senate Committee on Banking, Housing and Urban Development
</p>
<p>
    <span class="red">June 6, 2012</span> March on JP Morgan, the Federal Reserve and the SEC for investigation of Jamie Dimon.
<a href="../files/Press Release-OSEC-JPM-Loss.pdf">Press Release</a> responding to the JPM losses.
</p>
<br>
<p>
    <strong><h12>LIBOR Scandal</h12></strong>
</p>
<p>
   LIBOR stands for the London Interbank Offer Rate, which is a rate calculated by member banks that tracks their borrowing costs, and is the basis for hundreds of trillions of dollars of derivatives, mortgages and other credit instruments. Last summer, Barclays was caught submitting interest rates that were massaged - either inflated or deflated - so that they could profit off certain trades or make their books look better than they were. Further investigations revealed that the fixing of rates extended beyond Barclays and had much larger ramifications for the markets. 
</p>
<p>
    <span class="red">July 16, 2012</span> <a href="http://www.occupythesec.org/files/SOX_Letter.pdf"> Letter</a> to SEC Chairman Mary Schapiro requesting a <a href="http://occupythesec.nycga.net/2012/07/16/the-need-for-criminal-prosecutions-to-redress-the-bank-excesses-of-the-libor-scandal/">criminal investigation</a> for market manipulation.
</p>
</div>